
const NOTIFICATIONS_COLLECTION = 'notifications';
const POOLS_COLLECTION = 'pools';
const USERS_COLLECTION = 'users';

module.exports = {
  NOTIFICATIONS_COLLECTION,
  POOLS_COLLECTION,
  USERS_COLLECTION
};
