
const SUCCESS = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const DOES_NOT_EXIST = 404;
const CONFLICT = 409;
const SERVER_ERROR = 500;

module.exports = {
  SUCCESS,
  CREATED,
  BAD_REQUEST,
  DOES_NOT_EXIST,
  CONFLICT,
  SERVER_ERROR
};
